timezone: "Asia/Tokyo"

# ====== 1) RSSありの公式ブログ ======
feeds:
  - name: OpenAI Blog
    url: https://openai.com/blog/rss
    tags: [company, genai]

  - name: Google AI Blog
    url: https://ai.googleblog.com/atom.xml
    tags: [company, research]

  - name: Meta AI Blog
    url: https://ai.facebook.com/blog/feed/
    tags: [company, research]

  - name: Microsoft Research Blog
    url: https://www.microsoft.com/en-us/research/feed/
    tags: [company, research]

  - name: Stability AI Blog
    url: https://stability.ai/blog/rss.xml
    tags: [company, genai]

  - name: Hugging Face Blog
    url: https://huggingface.co/blog/rss.xml
    tags: [company, ml, huggingface]

  - name: NVIDIA Technical Blog
    url: https://developer.nvidia.com/blog/feed/
    tags: [hardware, inference, nvidia]

  - name: Adobe Firefly Blog
    url: https://blog.adobe.com/en/publish/rss.xml?topic=firefly
    tags: [creative, genai, adobe]

  - name: Apple ML Research
    url: https://machinelearning.apple.com/rss.xml
    tags: [ml, research, apple]

# ====== 2) RSSなし/不明：ニュース一覧から見出しキーワード抽出 ======
site_feeds:
  # --- AI企業 ---
  - name: Anthropic News
    url: https://www.anthropic.com/news
    include: ["AI","生成","Claude","自動化","エージェント","RAG","モデル","LLM"]
    exclude: ["採用","求人","法務","イベントのみ"]

  - name: Mistral AI News
    url: https://mistral.ai/news/
    include: ["AI","生成","自動化","エージェント","LLM","open weight"]
    exclude: ["採用","募集","求人"]

  - name: Cohere Blog
    url: https://cohere.com/blog
    include: ["AI","生成","RAG","LLM","エージェント","NLP","モデル"]
    exclude: ["募集","IR"]

  - name: Sakana AI News
    url: https://sakana.ai/
    include: ["AI","生成","自動化","研究","モデル","LLM"]
    exclude: ["採用","求人"]

  - name: Sony AI News
    url: https://ai.sony/
    include: ["AI","生成","自動化","研究","ロボット","モデル"]
    exclude: ["採用","求人"]

  # --- 建設・設備設計 ---
  - name: 清水建設 ニュース
    url: https://www.shimz.co.jp/company/about/news/
    include: ["AI","生成","自動化","BIM","DX]()
