
name: daily
on:
  schedule:
    - cron: '15 22 * * *'   # JST 07:15（GitHub は UTC）
  workflow_dispatch: {}
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - run: pip install -r requirements.txt
      - run: python main.py
      - name: Commit & Push
        run: |
          git config user.name "bot"
          git config user.email "bot@example.com"
          git add -A
          git commit -m "update $(date -u +'%F %T')" || echo "no changes"
          git push
